using FFXIVClientStructs.FFXIV.Component.GUI;
using Lumina.Text.ReadOnly;

namespace GubalLibrary;

/// <summary>
///     Writes SeString bytes into the UI, so formatting payloads survive the trip.
/// </summary>
/// <remarks>
///     <para>
///         Both targets have a <c>ReadOnlySpan&lt;byte&gt;</c> overload —
///         <c>AtkValue.SetManagedString</c> and <c>AtkTextNode.SetText</c> — and those are the only
///         ones that can carry formatting. Their <c>string</c> siblings marshal plain UTF-8 and do no
///         macro parsing, which is why every italic, colour and icon payload died on the way to the
///         screen while the text itself arrived intact.
///     </para>
///     <para>
///         <b>The null terminator is ours to add.</b> Those span overloads are generated by
///         FFXIVClientStructs' <c>[GenerateStringOverloads]</c>, and all they do is pin the span's
///         pointer and hand it to the native <c>byte*</c> function — they append nothing.
///         <see cref="ReadOnlySeString" />'s own bytes are not terminated either, so passing them
///         straight through would leave the game reading past the end of the buffer until it happened
///         upon a zero. Hence the copy: it exists solely to own that trailing byte.
///     </para>
///     <para>
///         A fresh array rather than a pooled or stack buffer. <c>new byte[]</c> is zero-initialised,
///         so the terminator costs nothing to write, and the allocation is per injected line — not per
///         frame, because both handlers guard on what is already on screen before they write. It is
///         dwarfed by the string this same code path allocates on every read.
///     </para>
/// </remarks>
internal static unsafe class SeStringWriter
{
    /// <summary>Replaces an addon's source value, before the game builds its text nodes from it.</summary>
    /// <remarks>
    ///     <c>SetManagedString</c> allocates through the game's allocator and takes ownership of its own
    ///     copy, so the buffer handed in here has no lifetime to manage.
    /// </remarks>
    public static void Write(AtkValue* value, ReadOnlySeString text)
    {
        if (value is not null)
        {
            value->SetManagedString(NullTerminated(text.Data.Span));
        }
    }

    /// <summary>Writes straight into a text node, for text the game did not route through a value.</summary>
    public static void Write(AtkTextNode* node, ReadOnlySeString text)
    {
        Write(node, text.Data.Span);
    }

    /// <summary>
    ///     Writes bytes captured earlier — used to hand the game's own line back untouched.
    /// </summary>
    /// <remarks>
    ///     Restoring has to go through bytes for the mirror-image of the reason writing does. The
    ///     string form of the game's line comes from <c>MemoryHelper.ReadSeStringAsString</c>, which
    ///     renders an italic payload as literal asterisks, so putting <em>that</em> back on screen
    ///     writes a visible <c>*Orion*</c> where the game had a properly italicised ship name.
    /// </remarks>
    public static void Write(AtkTextNode* node, ReadOnlySpan<byte> utf8)
    {
        if (node is not null && !utf8.IsEmpty)
        {
            node->SetText(NullTerminated(utf8));
        }
    }

    private static byte[] NullTerminated(ReadOnlySpan<byte> bytes)
    {
        var buffer = new byte[bytes.Length + 1];
        bytes.CopyTo(buffer);
        return buffer;
    }
}
